### ISSUE TITLE
time interval is the issue

### ISSUE THREAD

**Issue by umesh-swami07** [juliangruber/async-debounce#1]
if my method takes 100 miliseconds to perform the operation and i have provided time interval of 50 then it wont run and vice a versa. can any one comment on this.

**Comment by juliangruber** [comment]
there must be another problem. if you take a look at https://github.com/juliangruber/async-debounce/blob/master/example.js, the async function takes 200ms and the interval is 50ms, and it runs the way it should

**Comment by umesh-swami07** [comment]
Thanks for the prompt reply.. I will verify this once again and let you know.
