### ISSUE TITLE
No issue, but a question about setTimeout within the async function

### ISSUE THREAD

**Issue by thexs-dev** [juliangruber/async-debounce#2]
This should not be an issue, but more of my lack of understanding

I found the hard way that the async function (from your example) would not work if it isn't wrapped in a setTimeout call (even with no interval)

If I remove the setTimeout from async function, it'd run just the first time, because running stays true

Am I missing something, or it's just a must to always use the setTimeout in that function?

Thanks in advance, Fausto

**Comment by juliangruber** [comment]
ah, I guess it always expect it to be async...if your function isn't async, use this module instead: https://github.com/component/debounce
